### ISSUE TITLE
[Question] Possibility to customize nodes via CSS?

### ISSUE THREAD

**Issue by Nedgeva** [open-source-labs/Svelvet#80]
Hi everyone and thanks for quality software!
I've notices that nodes comes w/ hardcoded classnames w/o ability to pass custom node classname via config:
https://github.com/oslabs-beta/Svelvet/blob/1cd0841bf666691c83cb2f396043727ad4715848/src/lib/Nodes/index.svelte#L22-L36

So the question - is there any possibilities to customize nodes besides passing config values>

**Comment by mrusme** [comment]
It seems possible, although it's a bit hacky. Also I don't know exactly why but e.g. `var(--color-primary-500)` won't work for things like `color` or `border-color`.

```css
.Svelvet > .Nodes > .Node > .Node {
  color: #032277;
  box-shadow: none;
  font-family: var(--theme-font-family-heading);
  font-size: 12px;
}

.dark .Svelvet > .Nodes > .Node > .Node {
  color: #a5bdfd;
}

.Svelvet > .Edges > g > path {
  stroke: #0641e5;
}
```
